### ISSUE TITLE
No module named 'core.data_loader'

### ISSUE THREAD

**Issue by tslgithub** [clovaai/stargan-v2#1]
when start to train my data, run "python3 main.py --mode train.............."

Traceback (most recent call last):
  File "main.py", line 18, in <module>
    from core.data_loader import get_train_loader
ImportError: No module named 'core.data_loader'

**Comment by yunjey** [comment]
@tslgithub We added __init__.py in both the `core `and `metrics` directories. Could you please try again and let me know if the problem is resolved?

**Comment by jjandnn** [comment]
method 2：
import sys
sys.path +=['/usr/local/lib/python3.6/site-packages','/YOUR/HOME/PATH/stargan-v2']
