### ISSUE TITLE
load trained model error

### ISSUE THREAD

**Issue by 523997931** [clovaai/stargan-v2#108]
Hello,
I want to use my trained model to sample some picture, but I get the error:
RuntimeError: Error(s) in loading state_dict for Generator:
	Missing key(s) in state_dict: "encode.6.conv1.weight", "encode.6.conv1.bias", "encode.6.conv2.weight", "encode.6.conv2.bias", "encode.6.norm1.weight", "encode.6.norm1.bias", "encode.6.norm2.weight", "encode.6.norm2.bias", "decode.6.conv1.weight", "decode.6.conv1.bias", "decode.6.conv2.weight", "decode.6.conv2.bias", "decode.6.norm1.fc.weight", "decode.6.norm1.fc.bias", "decode.6.norm2.fc.weight", "decode.6.norm2.fc.bias", "decode.6.conv1x1.weight", "hpf.filter".

I use the commend to sample python main.py --mode sample --num_domains 3 --src_dir ./test/test --ref_dir ./test/ref/ --resume_iter 140000

**Comment by RizhaoCai** [comment]
Same issue. Have you solved it? @523997931
