### ISSUE TITLE
eval bug 

### ISSUE THREAD

**Issue by Johnson-yue** [clovaai/stargan-v2#11]
when compute FID and LPIPS  , mode = "latent" then ,the bug
`UnBoundLocalError: local variable 'loader_ref' referenced before assigment`

**Comment by yunjey** [comment]
@Johnson-yue Could you report the full error message?

**Comment by iPsych** [comment]
@yunjey 
I faced same error.
Calculating evaluation metrics...
Number of domains: 4
Preparing DataLoader for the evaluation phase...
Traceback (most recent call last):
  File "main.py", line 182, in <module>
    main(args)
  File "main.py", line 59, in main
    solver.train(loaders)
  File "/home/ipsych/ML/Stargan_v2/core/solver.py", line 170, in train
    calculate_metrics(nets_ema, args, i+1, mode='latent')
  File "/home/ipsych/.conda/envs/Pytorch_1_4_0/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ipsych/ML/Stargan_v2/metrics/eval.py", line 61, in calculate_metrics
    iter_ref = iter(loader_ref)
UnboundLocalError: local variable 'loader_ref' referenced before assignment

**Comment by iPsych** [comment]
It seems that in solver.py line 170,
`                calculate_metrics(nets_ema, args, i+1, mode='latent')
`
calls undefined loader_ref in eval.py.

**Comment by Johnson-yue** [comment]
@iPsych yes， when I train custom dataset， the num_domain is not 3 ， and it report this error

**Comment by iPsych** [comment]
@Johnson-yue Interestingly, I trained 7 domains successfully once, and now, training 4 domains model, and same error happens.

**Comment by yunjey** [comment]
Closing the issue, thinking that the question was answered.
Please reopen the issue as needed :)
