### ISSUE TITLE
"enforce fail at CPUAllocator.cpp" error in eval phase

### ISSUE THREAD

**Issue by iPsych** [clovaai/stargan-v2#13]
<img width="224" alt="Screen Shot 2020-04-29 at 8 32 11 PM" src="https://user-images.githubusercontent.com/28276515/80591561-e0b5fe00-8a58-11ea-8c7d-2ae4a6ee8377.png">

"enforce fail at CPUAllocator.cpp" error happens in eval phase, even the system is 128GB memory.
Does it expectable, and due to lack of enough memory?

**Comment by yunjey** [comment]
@iPsych If the memory is issue, decrease the `val_batch_size` argument [here](https://github.com/clovaai/stargan-v2/blob/master/main.py#L121).

**Comment by iPsych** [comment]
@yunjey adjusting val_batch_size works. 
Thanks.
