### ISSUE TITLE
Score numbers differ from the paper

### ISSUE THREAD

**Issue by affromero** [clovaai/stargan-v2#14]
Hello, the numbers you report here differ from the paper.
1. Is the version of the paper using the heatmaps? If yes, do you have numbers without heatmaps? They would help a lot.
2. Are these new numbers using the same experimental framework reported in the paper? Batch size, number of iterations, etc.?
3. I also found that some of the architectures do not match with the ones reported in the paper. For instance, the discriminator max_dim goes up to [512](https://github.com/clovaai/stargan-v2/blob/master/core/model.py#L256) (in the paper says 1024), and the mapping network [is different](https://github.com/clovaai/stargan-v2/blob/master/core/model.py#L202-L208) as well. Is there going to be an updated arxiv version?
4. [EDIT]. If AFHQ does not use heatmaps, why the numbers are also different from the paper?

Thank you.

**Comment by yunjey** [comment]
@affromero Please see the updated version: https://arxiv.org/abs/1912.01865
