### ISSUE TITLE
About generator

### ISSUE THREAD

**Issue by zhangqianhui** [clovaai/stargan-v2#15]
Hello, Does the generator need tanh? I can not find it in this project.
@yunjey  @youngjung

**Comment by yunjey** [comment]
@zhangqianhui The generator does not need to have the tanh function. It learns to output an appropriate range of images.

**Comment by zhangqianhui** [comment]
Thanks.

**Comment by zhangqianhui** [comment]
Recently, I try to implement starganv2 using tensorflow. But I got some unexpected results.
![图片](https://user-images.githubusercontent.com/7938702/80753090-41c7f980-8b5f-11ea-8418-9d2dc2afc0ba.png)

**Comment by Johnson-yue** [comment]
@zhangqianhui  hi， how did you fix this bug?? I have same question like this

**Comment by zhangqianhui** [comment]
Yeah I have solved this problem.

**Comment by zhangqianhui** [comment]
Do you use the tf code?

**Comment by Johnson-yue** [comment]
@zhangqianhui I use pytorch for re-implement before this released， and I have same question but I don't know why。
 would you release  you tf code about how to fixed it？？ I used tf for a while， so I can read it，

**Comment by zhangqianhui** [comment]
You can check the implementation of gp or the parameters of every module.
