### ISSUE TITLE
Curiosity about Adam Beta1=0

### ISSUE THREAD

**Issue by denadai2** [clovaai/stargan-v2#17]
Hi,
first of all congrats for the paper. I am curious about your choice of Adam parameters. Could you give more insights about Beta1=0? Why don't you use Momentum? 

Thank you!

**Comment by yunjey** [comment]
@denadai2 Thanks. We tried several values for `beta1` and `beta2` in the Adam optimizer and observed that the perfomance of `beta1=0` and `beta2=0.99` is the best. These setup is similar to the RMSProp optimizer, except the bias correction for the second moment `beta2` which makes initial training stable.

**Comment by yunjey** [comment]
@denadai2  Closing the issue, thinking that the question was answered.
Please reopen the issue as needed :)
