### ISSUE TITLE
Segmentation fault when align custom images

### ISSUE THREAD

**Issue by shiyingZhang90** [clovaai/stargan-v2#18]
Hi @yunjey , thanks for great work!
I followed your instruction to manually crop my own image and run the wing alignment, yet I get segmentation fault without any more error message. Please help

Error below:
UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Segmentation fault

**Comment by shiyingZhang90** [comment]
also, a follow up question -- is it possible to only change hair color using starganv2? I found it will change both skin color and hair color in demo video. Thanks

**Comment by skyflynil** [comment]
For some reason I got segmentation fault during align as well. It was crashing at
https://github.com/clovaai/stargan-v2/blob/5b26cbf183ee9e20019abe91384a3a8277b29bed/core/wing.py#L307
My issue was resolved by reinstall opencv using conda (to an old 3.x version) and of course at risk of breaking other stuff.

**Comment by rishsriv** [comment]
Thanks @skyflynil for the suggestion. I was facing the same issue. Upgrading to opencv 4.2 solved it for me. Apparently, this was [an issue](https://github.com/opencv/opencv/issues/16030) with opencv 4.1.2

`pip install opencv-python==4.2.0.34`

**Comment by shiyingZhang90** [comment]
Thanks @rishsriv @skyflynil my issue resolved after I upgrade to opencv 4.3

**Comment by youngjung** [comment]
It seems this issue is resolved.
Closing the issue.
Thanks @rishsriv @skyflynil .

**Comment by rublaman** [comment]
After 4 hours rendering, I had a "Segmentation fault". I've tried opencv 4.1.2, opencv 4.2.0.34 and opencv 3.4. Same results, "Segmentation fault"
![unknown](https://user-images.githubusercontent.com/52293654/85159499-e1e7f800-b25d-11ea-87ae-cd2f11f2b9e5.png)

**Comment by Mofafa** [comment]
> For some reason I got segmentation fault during align as well. It was crashing at
> https://github.com/clovaai/stargan-v2/blob/5b26cbf183ee9e20019abe91384a3a8277b29bed/core/wing.py#L307
> 
> 
> My issue was resolved by reinstall opencv using conda (to an old 3.x version) and of course at risk of breaking other stuff.

I met the same error, and I solved it using the method mentioned in this link: [https://github.com/opencv/opencv/issues/16030](url)

Add ` cv2.setNumThreads(1)`

**Comment by phanthaiduong22** [comment]
> After 4 hours rendering, I had a "Segmentation fault". I've tried opencv 4.1.2, opencv 4.2.0.34 and opencv 3.4. Same results, "Segmentation fault" ![unknown](https://user-images.githubusercontent.com/52293654/85159499-e1e7f800-b25d-11ea-87ae-cd2f11f2b9e5.png)

I have the same problem
