### ISSUE TITLE
The repository link seems to be wrong

### ISSUE THREAD

**Issue by ialhashim** [clovaai/stargan-v2#2]
In the Readme file the repo is not this one.

**Comment by yunjey** [comment]
@ialhashim Which link are you referring to?

**Comment by skyflynil** [comment]
I think he was talking about 
`git clone https://github.com/yunjey/stargan-v2.git`

**Comment by yunjey** [comment]
@skyflynil Thanks a lot! I wasn't aware of that mistake. Now, the link has been changed correctly.
