### ISSUE TITLE
Generate Image resolution higher than 256

### ISSUE THREAD

**Issue by shiyingZhang90** [clovaai/stargan-v2#20]
Is it possible to generate image with resolution 512 or 1024? I tried the img_size argument in main.py to change it to 512, yet I got following errors, seems like the model doesn't support other resolution?

RuntimeError: Error(s) in loading state_dict for Generator:
	Missing key(s) in state_dict: "encode.3.conv1x1.weight", "encode.7.conv1.weight", "encode.7.conv1.bias", "encode.7.conv2.weight", "encode.7.conv2.bias", "encode.7.norm1.weight", "encode.7.norm1.bias", "encode.7.norm2.weight", "encode.7.norm2.bias", "decode.7.conv1.weight", "decode.7.conv1.bias", "decode.7.conv2.weight", "decode.7.conv2.bias", "decode.7.norm1.fc.weight", "decode.7.norm1.fc.bias", "decode.7.norm2.fc.weight", "decode.7.norm2.fc.bias", "decode.7.conv1x1.weight". 
	size mismatch for from_rgb.weight: copying a param with shape torch.Size([64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3]).
	size mismatch for from_rgb.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).

**Comment by youngjung** [comment]
Our pre-trained model is capable of producing 256x256 image only.
There are more rooms to be improved in higher resolution.
You can try training the model from scratch with higher resolution with `img_size` argument but I suggest not to expect good results.

**Comment by eps696** [comment]
@shiyingZhang90 one can switch off resizing for source images to sample/process arbitrary resolutions (it's only reference images that must strictly follow the model). 
expect serious artifacts though: https://www.instagram.com/p/B_2Vud8FCBi

**Comment by yunjey** [comment]
Closing the issue, thinking that the question was answered.
Please reopen the issue as needed :)
