### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by BazzS** [clovaai/stargan-v2#22]
I'm new to Python, I've been studying it for a while. I found your project by chance and it really impressed me, I want to figure out how everything works and test it myself, but using istruction nothing works. When I write the command:
bash download.sh celeba-hq-dataset

download.sh: line 9: 
StarGAN v2
Copyright (c) 2020-present NAVER Corp.

This work is licensed under the Creative Commons Attribution-NonCommercial
4.0 International License. To view a copy of this license, visit
http://creativecommons.org/licenses/by-nc/4.0/ or send a letter to
Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
: No such file or directory
download.sh: line 38: wget: command not found
unzip:  cannot find or open ./data/celeba_hq.zip, ./data/celeba_hq.zip.zip or ./data/celeba_hq.zip.ZIP.
rm: ./data/celeba_hq.zip: No such file or directory

**Comment by youngjung** [comment]
You need to install `wget`.
Abundant helps are just one 'google' away.
