### ISSUE TITLE
Path error upon running the example you provided to transform a custom image

### ISSUE THREAD

**Issue by Remideza** [clovaai/stargan-v2#3]
Probably caused by windows, edited the line 58 of solver to link directly to the checkpoint instead

> Traceback (most recent call last):
  File "main.py", line 182, in <module>
    main(args)
  File "main.py", line 37, in main
    solver = Solver(args)
  File "D:\Documents\Desktop\StarGAN\core\solver.py", line 58, in __init__
    self.ckptios = [CheckpointIO(ospj(args.checkpoint_dir, '{:06d}_nets_ema.ckpt'), **self.nets_ema)]
  File "D:\Documents\Desktop\StarGAN\core\checkpoint.py", line 17, in __init__
    os.makedirs(os.path.dirname(fname_template), exist_ok=True)
  File "D:\Dev\Python\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] Path not found: '{:'

**Comment by youngjung** [comment]
Thank you for reporting the issue and a workaround.
It would help others working on windows.

**Comment by cloudweather** [comment]
Do you mind providing an example of how to link it directly to the checkpoint? Thank you

**Comment by Remideza** [comment]
Solder line 58 

> self.ckptios = [CheckpointIO(ospj(args.checkpoint_dir, '100000_nets_ema.ckpt'), **self.nets_ema)]

And 100000_nets_ema.ckpt is directly in the \expr\checkpoints folder

**Comment by jishulinbyte** [comment]
remove checkpoint.py line 17 checkpoint.py .And create expr in the root directory, and create checkpoints under expr.

**Comment by Gavin-Evans** [comment]
delete : , because os.path.join('expr/checkpoint', '{:06d}_nets.ckpt')  is  "{:06d}_nets.ckpt",  not "expr/checkpoint/{:06d}_nets.ckpt".
