### ISSUE TITLE
About AdaIN

### ISSUE THREAD

**Issue by yoyo-nb** [clovaai/stargan-v2#32]
Hello! I have a question about class AdaIN. 
In your implementation, you used `(1 + gamma) * self.norm (x) + beta` . Why don't you use `gamma * self.norm (x) + beta` ? Thank you.

**Comment by Johnson-yue** [comment]
it is the same ，because they have different initial bias value！！！

when initial gamma is 0 ， then use：
`(1 + gamma) * self.norm (x) + beta`

it is the same as

when initial gamma is 1 ， then use：
`gamma * self.norm (x) + beta`

**Comment by yoyo-nb** [comment]
Thank you！
