### ISSUE TITLE
multi-gpu training

### ISSUE THREAD

**Issue by newExplore-hash** [clovaai/stargan-v2#33]
hi，I found that the actual training time was longer than the time mentioned in the paper，could you release the multi-gpu code? or is there any tips for me to change this code to multi-gpu? (i have tried to make the change , but there is some problem, maybe the library of Munch not support multi-gpu operation)

tks

**Comment by yunjey** [comment]
@newExplore-hash We do not support the multi-gpu training. Training takes about 3 days as mentioned in the paper. Please see the [updated version](https://arxiv.org/abs/1912.01865).
