### ISSUE TITLE
Update step with reference images

### ISSUE THREAD

**Issue by vllsg** [clovaai/stargan-v2#34]
Hi, I was wondering why the style encoder isn't updated when computing the losses with reference images.
Thank you for your work.

**Comment by toculin38** [comment]
I am not familiar with PyTorch but I guess it's because of optims.style_encoder.step() is not called after backward().

**Comment by lavoiems** [comment]
Why isn't optims.style_encoder.step() not called? Shouldn't it be called?

**Comment by kevhahn97** [comment]
https://github.com/clovaai/stargan-v2/issues/44
:)
