### ISSUE TITLE
Get output image

### ISSUE THREAD

**Issue by Nerdyvedi** [clovaai/stargan-v2#37]
Is there an option to get the output image only.  On running the model, I am getting the video as the output. 
I only want to save the generated images. 

Thank you for open sourcing such an amazing work.

**Comment by yunjey** [comment]
@Nerdyvedi Sorry for a late reply. See https://github.com/clovaai/stargan-v2/blob/master/core/utils.py#L101-L118. You can easily change the code to save generated images only.

**Comment by Nerdyvedi** [comment]
Thank you
