### ISSUE TITLE
(Help) What is causing this output?

### ISSUE THREAD

**Issue by gigadeplex** [clovaai/stargan-v2#39]
When running sample, this is the reference.jpg I get.

![reference](https://user-images.githubusercontent.com/35807763/82743362-b3fcba00-9d6a-11ea-9bd5-df1a629156e3.jpg)

**Comment by yunjey** [comment]
@gigadeplex These are the results of the randomly initialized generator. To get reasonable results, train the model or download the pre-trained model.

**Comment by gigadeplex** [comment]
@yunjey Hi, thank you for replying. This result is from after downloading the generator. Prior to getting this result, I received an error from solver.py in line:
`self.ckptios = [CheckpointIO(ospj(args.checkpoint_dir, '{:06d}_nets_ema.ckpt'), **self.nets_ema)]`
so I changed it to:
`self.ckptios = [CheckpointIO(ospj("expr/checkpoints/celeba_hq/100000_nets_ema.ckpt"))]`
Then I got that result.

**Comment by gigadeplex** [comment]
@yunjey Ok but this is from after downloading the generator, I received and error from line:
`self.ckptios = [CheckpointIO(ospj(args.checkpoint_dir, '{:06d}_nets_ema.ckpt'), **self.nets_ema)]` 
which I change to:
`self.ckptios = [CheckpointIO("expr/checkpoints/celeba_hq/100000_nets_ema.ckpt")]`
Then I got this output. Did I do something wrong?
