### ISSUE TITLE
mode of sample and align

### ISSUE THREAD

**Issue by newExplore-hash** [clovaai/stargan-v2#4]
when i execute command of python main.py --mode sample --num_domains 2 --resume_iter 100000 --w_hpf 1 \
               --checkpoint_dir expr/checkpoints/celeba_hq \
               --result_dir expr/results/celeba_hq \
               --src_dir assets/representative/celeba_hq/src \
               --ref_dir assets/representative/celeba_hq/ref
or python main.py --mode align \
               --inp_dir assets/representative/custom/female \
               --out_dir assets/representative/celeba_hq/src/female

the following error occurred:
Traceback (most recent call last):
  File "main.py", line 182, in <module>
    main(args)
  File "main.py", line 37, in main
    solver = Solver(args)
  File "/root/work/stargan-v2/core/solver.py", line 34, in __init__
    self.nets, self.nets_ema = build_model(args)
  File "/root/work/stargan-v2/core/model.py", line 300, in build_model
    fan = FAN(fname_pretrained=args.wing_path).eval()
  File "/root/work/stargan-v2/core/wing.py", line 213, in __init__
    self.load_pretrained_weights(fname_pretrained)
  File "/root/work/stargan-v2/core/wing.py", line 217, in load_pretrained_weights
    checkpoint = torch.load(fname)  # map_location=torch.device('cpu'))
  File "/root/anaconda3/envs/stargan-v2/lib/python3.6/site-packages/torch/serialization.py", line 526, in load
    if _is_zipfile(opened_file):
  File "/root/anaconda3/envs/stargan-v2/lib/python3.6/site-packages/torch/serialization.py", line 76, in _is_zipfile
    if ord(magic_byte) != ord(read_byte):
TypeError: ord() expected a character, but string of length 0 found

and i have installed all dependencies and downloaded the corresponding datasets and checkpoints as your description in repository. could you tell me how to solve this problem?  tks much

**Comment by xiaochuangshu** [comment]
Hello, I have the same problem, have you solved this problem? If so, can you give me some help

**Comment by LeesCode** [comment]
I have same problem,don't know why.Do you solve it?Thx

**Comment by LeesCode** [comment]
> Hello, I have the same problem, have you solved this problem? If so, can you give me some help

**Comment by LeesCode** [comment]
I fix it out.Because when you execute 
bash download.sh celeba-hq-dataset
bash download.sh pretrained-network-celeba-hq
bash download.sh wing
It cann't download 100000_nets_ema.ckpt  wing.ckpt  celeba_lm_mean.npz.You have to use the link to download them,then put them in the right files.
