### ISSUE TITLE
how to solve this error {No such file or directory: 'expr/checkpoints/wing.ckpt'}

### ISSUE THREAD

**Issue by engineer-38** [clovaai/stargan-v2#43]
FileNotFoundError: [Errno 2] No such file or directory: 'expr/checkpoints/wing.ckpt'

**Comment by yunjey** [comment]
@engineer-38 See https://github.com/clovaai/stargan-v2#datasets-and-pre-trained-networks. Download the network checkpoint.

**Comment by yunjey** [comment]
Closing the issue, thinking that the question was answered.
Please reopen the issue as needed :)
