### ISSUE TITLE
Using number of iterations but not Epoch for training

### ISSUE THREAD

**Issue by tranctan** [clovaai/stargan-v2#47]
Hi, may i have a question about the implementation in solver.py of training step. In which the number of iterations (steps) is particularly used instead of number of epochs ?

**Comment by yunjey** [comment]
@tranctan Because the number of images in each dataset is different, we used `num_iters` for simplicity/consistency. Note that you should set different `num_epochs` values for each dataset.

**Comment by tranctan** [comment]
Thanks ! It's much clearer now !

May I ask a further thing that whether the number of instances in each attribute value (black/blond/red hair) needs to be balance ? Or imbalance is not important.

**Comment by yunjey** [comment]
@tranctan We addressed those imbalance issue by using [balanced sampler](https://github.com/clovaai/stargan-v2/blob/master/core/data_loader.py#L81-L85). The dataset does note requires balanced classes.

**Comment by tranctan** [comment]
Thanks for your information ! It makes sense now !

I'm closing this issue.
