### ISSUE TITLE
Heatmaps

### ISSUE THREAD

**Issue by affromero** [clovaai/stargan-v2#5]
Hello, nice work.
I have a couple of doubts regarding the heatmaps.
1. Could you please elaborate on [these values](https://github.com/clovaai/stargan-v2/blob/master/core/wing.py#L477-L537)? Why resizing and shifting heatmaps and why those numbers for different regions of the face (`x` and `x2`)? In the main paper, there is nothing about heatmaps or keypoints, so I am trying to understand the intuition.

2. Are `wing.ckpt` pre-trained weights the same as in this [work](https://github.com/protossw512/AdaptiveWingLoss), or do they differ in some way? 

3. Does CelebA_HQ work without heatmaps?

Thanks :)

**Comment by youngjung** [comment]
Hi, thanks for your interest.

1. Those heatmaps indicate the regions where we want to keep the source image stronger.
`x` is for a coarse layer and `x2` is for finer layer. (similar definition of coarse and fine in StyleGAN)

2. Yes, the same.

3. Yes it still works. Just eyes, nose and mouth of the source image will be less-reflected.

Do these answer your question?

**Comment by affromero** [comment]
Yes, pretty much. 
The last remaining thing is about the resizing and shifting of the heatmaps.

**Comment by youngjung** [comment]
Ah, sorry I missed that part.
Those are our customization to fit region to eye-nose-mouth-chin part.
The region looks like below.
`source`
`x * source`
`x2 * source`
<img width="200" alt="image" src="https://user-images.githubusercontent.com/45905238/80436088-427f4680-8939-11ea-8569-b0fb6bb661c4.png">
