### ISSUE TITLE
Manage domain (attribute) as StarGANv1 

### ISSUE THREAD

**Issue by HyelinNAM** [clovaai/stargan-v2#50]
If you look at the StarGAN v1, one image can belong to multiple domains. It treats attributes by txt file.
And my datasets set up that way now. (Every image belongs to multiple domains.) Images are in one folder and save labels using a CSV file. Should I save the image by domain? Is there any good way to solve my problem? Thanks.

안녕하세요. 한국인이라서 혹시나 보실까하고 한국어로도 질문 남깁니다. 위에서 질문 드린것과 같이, 지금 저는 이미지들이 한 폴더에 있고 각 이미지가 여러 도메인에 속하는 상태입니다. (사진 A가 여자 도메인에 속하는 동시에 금발 도메인에 속해서 두 도메인의 학습 모두에 사진 A를 사용하려 합니다.) 제시해주신대로 데이터를 저장하려면 여러 폴더에 같은 사진이 저장되어야 하는데 이는 너무 번거롭고 용량도 많이 차지해서 다른 좋은 방법이 있을지 궁금합니다. 감사합니다. :)

**Comment by yunjey** [comment]
@HyelinNAM  안녕하세요 혜린님, 

StarGAN v2를 multi-attribute에 대해 학습시킬 때는, Binary 형태의 multi-hot label들을 Categorical 형태의 one-hot label로 바꾸시는 게 좋을 것 같습니다. 예를 들어, 학습에 사용하려는 Attribute이 성별(female/male)과 머리색(blonde/black)이면, 총 4개의  domain (female+blonde, female+black, male+blonde, male+black)으로 데이터셋을 구분지어서 학습시키면 될 듯 합니다. 저희도 StarGAN v2를 multi-attribute 세팅에 대해서 학습시켜본 적이 없어서 잘 될지는 모르겠네요. 나중에 실험해보시고 재밌는 결과 나오면 공유해주시면 감사하겠습니다 :)

**Comment by HyelinNAM** [comment]
답변 감사합니다. 좋은 결과 있었으면 좋겠네요. 좋은 하루 되세요! :)
