### ISSUE TITLE
Can you release the nets.ckpt and optims.ckpt?Or tell me how to split the trainning set and validation set?

### ISSUE THREAD

**Issue by helloahuzw** [clovaai/stargan-v2#55]

**Comment by Johnson-yue** [comment]
the dataset have splited train set and validation set done, you should download dataset first

**Comment by helloahuzw** [comment]
OK，thank you very much

**Comment by renmengyuan** [comment]
> OK，thank you very much

Is there any link about the nets.ckpt and optims.ckpt?
