### ISSUE TITLE
missing `celeba_lm_mean.npz` for `align` mode

### ISSUE THREAD

**Issue by jojanzing** [clovaai/stargan-v2#61]
Hi, nice repo and great work! 

~Unfortunately, I am running into an issue when I try to use the pretrained celeba model on my own images. As per the readme, I want to crop and align the images first, but when I try run align mode, I get an error message that `celeba_lm_mean.npz` cannot be found.~

~Is there any chance you chould share this file with us?~

Found it! Sorry =P

**Comment by tcxia** [comment]
where is the "celeba_lm_mean.npz"

**Comment by YangGangZhiQi** [comment]
I have encountered the same problem? Is there anyone could help me?
