### ISSUE TITLE
about nets_ema

### ISSUE THREAD

**Issue by Feynman1999** [clovaai/stargan-v2#62]
can you explain how the `nets_ema` works in your code, and why we need it, thanks!

**Comment by gsotnikov** [comment]
The main idea is that due the adversarial game, networks (Gen, Style Enc, Mapping Net) oscillate badly in parameter space after each gradient step. It was noticed that by storing smoothed versions of them w.r.t. previous values of parameters can significantly improve the quality of synthesized images. You can find details in the paper https://openreview.net/forum?id=SJgw_sRqFQ

**Comment by yunjey** [comment]
@gsotnikov Thanks for your answer! :)
