### ISSUE TITLE
query regarding pre-trained model 

### ISSUE THREAD

**Issue by MukundVarmaT** [clovaai/stargan-v2#64]
Hi, thank you for sharing this amazing work. 

I had one question regarding the pre-trained model. Since the labels for the domain are decided based on 
`domains = os.listdir(root)` while training, doesn't it lead to variability across systems as the order could be different (i.e) the pre-trained model provided could be trained with 1-male, 0-female and when I do the listdir operation on my system I could get 1-female and 0-male. 

It would be really great if you could clarify the same. Thank you once again.

**Comment by youngjung** [comment]
Hi, thank you for showing interest in our work.
In our system, female comes in front of male. You can use `domains = sorted(os.listdir(root))` for the same behavior.

**Comment by MukundVarmaT** [comment]
oh ok, thank you for the quick reply.
