### ISSUE TITLE
enhancement - support dockerfile

### ISSUE THREAD

**Issue by johndpope** [clovaai/stargan-v2#7]
facebook reference file
https://github.com/facebookresearch/detectron2/blob/0c045f269d69ecbf8a4c978ee9a9f61a46861b91/docker/Dockerfile

**Comment by fpaupier** [comment]
I maintain a simpler fork of this repo with a Dockerfile and a docker compose to ease reproduction of result. You can find it here https://github.com/fpaupier/stargan-v2
