### ISSUE TITLE
How to get the high resolution translation images  ?

### ISSUE THREAD

**Issue by zxy2020** [clovaai/stargan-v2#73]
Hello, everyone ,I try to train and get  the high resolution imgs,such as --img_size=1024,

But,the result  is bad and artificial.

How can I  imporve the result?

Do  I  need to modify the   model  of discriminator ?

**Comment by yunjey** [comment]
@zxy2020 I do not expect the quality to be maintained when you increase the resolution. I recommend to choose different values for hyperparameters (e.g., loss weights)

**Comment by zxy2020** [comment]
Thank you !
