### ISSUE TITLE
data sets and pretrained models unable to access

### ISSUE THREAD

**Issue by baymak** [clovaai/stargan-v2#74]
Dropbox URLs gives "Error (404)
We can't find the page you're looking for."

It was working a few days ago. All of them give same error

**Comment by yunjey** [comment]
@baymak Which URLs did you mean? You can see the direct links to access datasets and pre-trained models [here](https://github.com/clovaai/stargan-v2/blob/master/download.sh#L14).

**Comment by baymak** [comment]
Hello Yunjey, None of the dropbox links in download.sh file unreachable two days ago(datasets, pretained models, wings etc). I have checked it now and it works. Thank you . When this issue appeared I was able to reach my personel dropbox links. So dropbox was working fine. Anyhow it seems everything is normal.

**Comment by benquick123** [comment]
Hi,
I'm writing this, because I have the same problem. I can't download any of the pretrained models and datasets. Can you help me solve this problem?
