### ISSUE TITLE
Is there any way to fix RuntimeError: CUDA error: out of memory error?

### ISSUE THREAD

**Issue by smartshk** [clovaai/stargan-v2#95]
I've run this model with 16GB RAM and nvidia RTX2070 8GB gpu.

I gave batch size only 2, but it keeps showing this error when it tries to save samples. 

Is there any way to reduce memory usage when training? Or Is the only way buying or upgrading gpu memory?

**Comment by eps696** [comment]
there were helpful advises and solutions in the old issues, you may want to look up it first
